<div class="row">

    <div class="col-md">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Painel de Controle') ?></h3>
            </div>
            <div class="panel-body">
                <p></p>

            </div>
        </div>
    </div>

</div>

<div class="jumbotron">
    <p><img src="img/logoicon_319x300.png" class="center-block"/></p>
</div>