<div class="jumbotron">
    <p><img src="img/logoCx300.png" class="center-block"/></p>
</div>

<div class="row">

    <div class="col-md">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Sobre') ?></h3>
            </div>
            <div class="panel-body">
                <p>Ferramenta que auxilia na consultoria de licitações.</p>

            </div>
        </div>
    </div>
</div>


