<div class="jumbotron">
    <p><img src="img/logoicon_319x300.png" class="center-block"/></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('E-commerce') ?></h3>
            </div>
            <div class="panel-body">
                <p>Especializado em atender a pequena e média empresa, a ZedNet oferece um pacote básico para quem esta querendo montar uma loja simples ou um catálogo online dos seus produtos.</p>

            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Site e Blog') ?></h3>
            </div>
            <div class="panel-body">
                <p>O WorPress é a ferramente de CMS mais fácil de utilizar. Este é o motivo de tanto sucesso entre os blogs e sites institucionais.</p>

            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Solução Personalizada') ?></h3>
            </div>
            <div class="panel-body">
                <p>Muitas vezes apenas um site institucional não atende as necessidades de uma empresa. Algumas empresas necessitam de sistemas que as auxiliem nas tarefas diárias, muitas até tem os seus negócios baseados em Sistemas Web personalizados.</p>
            </div>
        </div>
    </div>
</div>
